server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB


  security:
    user:
      name: admin
      password: 2527

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel5.cloudtype.app:32319/cafe-flow
    username: root
    password: 2527

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG


app:
  jwt:
    secret: "afee9ff139300837761676667d913ed901b7d6a7119053311e1b2e63fd47a48e"
    expiration: 86400000


iamport:
  api-key: "7655673661637031"
  api-secret: "9e0qf4EneZXs0MIX7LQbJvytgSoC445Lzcpylz8yRsjziNZZmYFk8reUL4H3bZdHgha7o71ndecmO5Vt"

kakao:
  client_id: 30ade00e0da2a659ae78956bda373c62
  redirect_uri: http://localhost:8080/api/auth/kakao-code